name: the_movie_db
description: Test project on flutter framework

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.11.1
  provider: ^6.0.1
  http: ^0.13.4
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  injectable: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^1.10.0
  injectable_generator: ^1.0.4

flutter:
  uses-material-design: true